project_name: gogo

before:
  hooks:
    - go mod tidy
    - go get sigs.k8s.io/yaml
    - go generate

builds:
  -
    main: .
    binary: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - "386"
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: "386"
    ldflags: "-s -w -X 'github.com/chainreactors/gogo/v2/internal/core.ver=={{ .Tag }}'"
    flags:
      - -trimpath
      - -tags=forceposix
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    no_unique_dist_dir: true

upx:
  -
    enabled: true
    goos: [linux, windows]

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format: binary

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
      - '^MERGE'
      - "{{ .Tag }}"
      - "^docs"

#release:
#  github:
#    owner: chainreactors
#    name: gogo
#  draft: true
